### ISSUE TITLE
Need Help PR for "Learn more about data storage..."

### ISSUE THREAD

**Issue by MaskofThoro** [gamejolt/doc-help#60]
The Data Storage tab on Dashboard-->Game API has the below copy with a needed help link.

"Data Storage Items
You can use the API to store data... in the cloud! All stored data items will show up here.

Currently, you can only view (and remove) globally stored data items. Stored user data items are not viewable at this time.

Learn more about data storage..."

**Comment by indiegamehunt** [comment]
Page created in PR #61
